### ISSUE TITLE
BlackPearlEonBrowser-5.0.11.dmg is damaged 

### ISSUE THREAD

**Issue by joanmarcriera** [SpectraLogic/ds3_java_browser#311]
Hi, 

With macOS 10.15.4 the EonBrowser 5.0.11 can not start, looks like the file is damaged. 

The previous version 5.0.10 works, but it asks to receive "keystrokes from any application" which I'm not going to grant since it feels like it has a keylogger installed. 

Best regards
Marc

**Comment by rpmoore** [comment]
Hi @joanmarcriera. Both of these issues are related to recent changes by Apple. I have not seen the keystrokes message yet, but it appears to be a common issue with may applications. The browser may work without it, but I cannot say which features will or will not work.

For the installer, Apple added extra signing steps that it requires third party apps to go through before they're allowed to run. We're currently in the process of attempting to get this signing working, but it is proving more difficult than we thought. There is a work around for it, but it's not the most straightforward process. I can post it for you if you'd like.

**Comment by joanmarcriera** [comment]
I've used the 5.0.10 to see how the simulator worked, that was OK for me.

**Comment by rpmoore** [comment]
If you do want to use 5.0.11 you can install the dmg like you normally would, but prior to running it you can access the command line, cd to /Applications and run `sudo xattr -cr BlackPearlEonBrowser.app` which will allow you to run the browser.
