### ISSUE TITLE
Mac Signing Issues showing as damaged install

### ISSUE THREAD

**Issue by rpmoore** [SpectraLogic/ds3_java_browser#312]
Recently Apple made changes to their requirements for signing and due to this every dmg we've generated now needs this additional validation logic. This is not proving to be straightforward and may require re-packaging of the browser. 

However, there is a workaround that will allow the browser to operate even without the extra signing. In order to execute this workaround, open the shell and execute the following steps.

1. `cd /Applications`
2. execute `sudo xattr -cr BlackPearlEonBrowser.app`

The browser should now run.

I'll use this issue to track the progress of the fix.

**Comment by jackielii** [comment]
just installed and tried on MacOS 13.2.1, works without an issue.

**Comment by hyz2993** [comment]
Sorry for digging this. Just to say you will need to right click it and click open to make it run for the first time. Double clicking for the first time will still get 'damaged' alert.

**Comment by richloweitv** [comment]
Have just tried the EON Browser with MacOS Sequoia and the workaround didn't work. Will their be any new builds for this OS version?

**Comment by mauriciope** [comment]
@rpmoore Hello Ryan, I hope you are well.
I've been given this solution to deploy to our Mac devices (macOS Sequoia) and I'm having the same problem when trying to run the app. You closed this issue, is there another one that you are tracking to fix this?
Thank you
